// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8AyVzhugFd5pRA3t8hGwx8nLXOOGYj7k',
    appId: '1:191720813275:web:33671bf2f6de3db47152fe',
    messagingSenderId: '191720813275',
    projectId: 'expense-tracker-d5e4b',
    authDomain: 'expense-tracker-d5e4b.firebaseapp.com',
    storageBucket: 'expense-tracker-d5e4b.firebasestorage.app',
    measurementId: 'G-L9PWSGFP32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGL40wS--BFKeQbv2Vaz83Iao_Ke1T3Y',
    appId: '1:191720813275:android:e119b407bd9b35ee7152fe',
    messagingSenderId: '191720813275',
    projectId: 'expense-tracker-d5e4b',
    storageBucket: 'expense-tracker-d5e4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAofyxZvxw3ViOoDxbM1nLwgupT_P0ZNOQ',
    appId: '1:191720813275:ios:24e7826fc7ee63d87152fe',
    messagingSenderId: '191720813275',
    projectId: 'expense-tracker-d5e4b',
    storageBucket: 'expense-tracker-d5e4b.firebasestorage.app',
    iosBundleId: 'com.example.expenceTracker',
  );
}
